inputs:
  #fIn: /Users/lucamicheletti/cernbox/JPSI/Jpsi_pp_cross_section_run3/mch_trk_eff/AnalysisResults_LHC24_pass1_MinBias.root
  fIn: /Users/lucamicheletti/cernbox/JPSI/Jpsi_pp_cross_section_run3/mch_trk_eff/AnalysisResults_LHC25c3b.root

outputs:
  #fOut: /Users/lucamicheletti/cernbox/JPSI/Jpsi_pp_cross_section_run3/mch_trk_eff/Histograms_trk_eff_LHC24_pass1_MinBias.root
  fOut: /Users/lucamicheletti/cernbox/JPSI/Jpsi_pp_cross_section_run3/mch_trk_eff/Histograms_trk_eff_LHC25c3b.root