inputs:
  path: /Users/lucamicheletti/cernbox/JPSI/Jpsi_pp_ref_cross_section_run3/MC
  production: LHC25g9/Runs/559348
  prefixGen: AnalysisResults # [AnalysisResults_dq_efficiency_with_assoc, AnalysisResults]
  prefixRec: AnalysisResults # [AnalysisResults_dq_efficiency_with_assoc, AnalysisResults]
  assocType: std_association
  sigGen: Jpsi
  sigRec: mumuFromJpsi
  cuts: [matchedMchMid]
  #cuts: [muonLowPt210SigmaPDCA]
  hlistGen: analysis-same-event-pairing/output
  listGen: MCTruthGenSel
  #histGen: Pt_Rapidity # dq-efficiency
  histGen: PtMC_YMC # dq-efficiency-with-assoc
  hlistRec: analysis-same-event-pairing/output
  listRec: PairsMuonSEPM
  histRec: Mass_Pt_Rapidity
  # Integrated Pt and Rap bins for THn, TH2 projections
  # Keep the same limits also in the differential bins!
  minPtBinInt: 0.0
  maxPtBinInt: 20.0
  minRapBinInt: 2.50
  maxRapBinInt: 4.00
  #ptBins: [0.0, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 7, 8, 10, 15, 20]
  #rapBins: [2.50, 2.75, 3.00, 3.25, 3.50, 3.75, 4.00]
  #ptBins: [0.0, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 10.0, 20.0]
  #rapBins: [2.50, 2.75, 3.00, 3.25, 3.50, 3.75, 4.00]
  #ptBins: [0.0, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 10.0, 20.0]
  #rapBins: [2.50, 2.75, 3.00, 3.25, 3.50, 3.75, 4.00]
  ptBins: [0.0, 20.0]
  rapBins: [2.50, 4.00]
  #ptBins: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 7.0, 10.0, 20.0]
  #rapBins: [2.50, 4.00]
  #ptBins: [0.0, 20.0]
  #rapBins: [2.50, 2.75, 3.00, 3.25, 3.50, 3.75, 4.00]

scan:
  path: /Users/lucamicheletti/cernbox/JPSI/Jpsi_pp_ref_cross_section_run3/MC/LHC25g9/Runs
  runList: run_list.txt
  fileName: axe_integrated_std_association_Jpsi

outputs:
  path: /Users/lucamicheletti/cernbox/JPSI/Jpsi_pp_ref_cross_section_run3/MC
  prefix: axe_integrated # [integrated, pt_dependence, rap_dependence]