inputs:
  #fIn: mch_trk_eff/AnalysisResults_LHC25ae_pass2.root
  #fIn: mch_trk_eff/AnalysisResults_LHC25i4.root
  fIn: mch_trk_eff/without_pt_cut/AnalysisResults_LHC25ae_pass2.root
  #fIn: mch_trk_eff/without_pt_cut/AnalysisResults_LHC25i4.root

outputs:
  #fOut: mch_trk_eff/Histograms_trk_eff_LHC25ae_pass2.root
  #fOut: mch_trk_eff/Histograms_trk_eff_LHC25i4.root
  fOut: mch_trk_eff/without_pt_cut/Histograms_trk_eff_LHC25ae_pass2.root
  #fOut: mch_trk_eff/without_pt_cut/Histograms_trk_eff_LHC25i4.root
  #fOutCorrMap: mch_trk_eff/mch_trk_eff_LHC25ae.root
  fOutCorrMap: mch_trk_eff/without_pt_cut/mch_trk_eff_LHC25ae.root