inputs:
  path: /Users/garetti/cernbox_all/analysis/JPsi_Psi2S_ratio/MC/pp_ref
  production:  # [LHC25c3, LHC25c3, LHC25c3b, LHC25g8] the second LHC25c3 is obtained with 2 AnalysisResults.root
  prefixGen: AnalysisResults # [AnalysisResults_dq_efficiency_with_assoc, AnalysisResults_dq_efficiency_gen_with_assoc, AnalysisResults_dq_efficiency_gen_with_assoc, AnalysisResults_dq_efficiency_gen_with_assoc]
  prefixRec: AnalysisResults # [AnalysisResults_dq_efficiency_with_assoc, AnalysisResults_dq_efficiency_rec_with_assoc, AnalysisResults_dq_efficiency_rec_with_assoc, AnalysisResults_dq_efficiency_rec_with_assoc]
  assocType: 
  sigGen: Jpsi
  sigRec: mumuFromJpsi
  cuts: [matchedMchMid]
  hlistGen: analysis-same-event-pairing/output
  listGen: MCTruthGenSel
  #histGen: Pt_Rapidity # dq-efficiency
  histGen: PtMC_YMC # dq-efficiency-with-assoc
  hlistRec: analysis-same-event-pairing/output
  listRec: PairsMuonSEPM
  histRec: Mass_Pt_Rapidity
  # Integrated Pt and Rap bins for THn, TH2 projections
  # Keep the same limits also in the differential bins!
  minPtBinInt: 0.0
  maxPtBinInt: 20.0
  minRapBinInt: 2.50
  maxRapBinInt: 4.00
  #ptBins: [0.0, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 7, 8, 10, 15, 20]
  #rapBins: [2.50, 2.75, 3.00, 3.25, 3.50, 3.75, 4.00]
  #ptBins: [0.0, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 10.0, 20.0]
  #rapBins: [2.50, 2.75, 3.00, 3.25, 3.50, 3.75, 4.00]
  #ptBins: [0.0, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 10.0, 20.0]
  #rapBins: [2.50, 2.75, 3.00, 3.25, 3.50, 3.75, 4.00]
  #ptBins: [0.0, 20.0]
  #rapBins: [2.50, 4.00]
  #ptBins: [0.0, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 10.0, 20.0]
  #rapBins: [2.50, 4.00]
  ptBins: [0.0, 2.0, 4.0, 6.0, 12.0, 20.0]
  rapBins: [2.50, 2.75, 3.00, 3.25, 3.50, 3.75, 4.00]

outputs:
  path: /Users/garetti/dq_fitter_lastV/dq_fitter_github
  prefix: mc_checks # [integrated, pt_dependence, rap_dependence]