---
inputs:
  pathFileDataPt: /Users/garetti/dq_fitter_lastV/dq_fitter_github/analysis/pp_ref/matchedMchMid/output/pass_stdAssoc_inputShapes/Pt_syst
  fileNameDataPt: systematic_sig_Jpsi.txt
  pathFileDataRap: /Users/garetti/dq_fitter_lastV/dq_fitter_github/analysis/pp_ref/matchedMchMid/output/pass_stdAssoc_inputShapes/Rap_syst
  fileNameDataRap: systematic_sig_Jpsi.txt
  pathFileDataCentr: 
  fileNameDataCentr: 
  pathAO2D: /Users/garetti/dq_fitter_tails/inputShapes/AO2D.root
  beamType: pp
  ptCut: 0.7
  ptMin: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 8.0, 12.0]
  ptMax: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 8.0, 12.0, 20.0]
  rapMin: [2.50, 2.75, 3.00, 3.25, 3.50, 3.75]
  rapMax: [2.75, 3.00, 3.25, 3.50, 3.75, 4.00]
  centrMin: [0.0, 20.0, 40.0, 60.0]
  centrMax: [20.0, 40.0, 60.0, 90.0]
